config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  get '/home', to: 'home#index'

  get '/devices', to: 'my_devices#index' 
  get '/devices/new', to: 'my_devices#new'
  post '/devices', to: 'my_devices#create'

  namespace :v1 do
    get '/settings', to: 'settings#getSettings' 
    post '/authenticate', to: 'authentication#create'
    post '/auto_login', to: 'authentication#auto_login'
    post '/sign_up', to: 'user#create'
    
    
    get '/get_pebbles', to: 'pebble#getPebbles'
    post '/create_pebble', to: 'pebble#create'
    post '/share_pebble', to: 'pebble#share'
    post '/save_token', to: 'mobile_device#registerToken'
    post '/delete_token', to: 'mobile_device#deleteToken'

  end

end

app/controllers/my_devices_controller.rb
class MyDevicesController < ApplicationController

    def index
    end 

    def new
        @device = Device.new
    end

    def create
        @device = Device.new(device_params)
        if @device.save
          puts "Device successfully created"
        else
          puts "Something went wrong"
        end
        redirect_to devices_path
    end
    

    private

    def device_params
      params.require(:device).permit(:device_name, :device_port, :device_type)
    end 

end

app/helpers/my_devices_helper.rb
module MyDevicesHelper
end

app/views/my_devices/_form.html.erb
<%= form_with model: @device do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :device_name %>
  </div>

  <div>
    <%= form.label :type %><br>
    <%= form.text_area :device_type %>
  </div>

  <div>
    <%= form.label :port %><br>
    <%= form.text_area :device_port %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/my_devices/index.html.erb
<h1>MY Devices</h1>

<%= link_to 'Home', root_path %>
<br/>
<%= link_to 'Add new device', devices_new_path %>

app/views/my_devices/new.html.erb
<h1>Add Device Here</h1>

<%= render 'form', device: @device %>